development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: blog_dev
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: blog_test
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: blog_prod
  username: postgres
  password:
